name: "Golden: x86 CET Shadow Stack"

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/golden-build.yml
    with:
      rule: x86-cet-shstk
      aarch64: false
      armv7: false
